ENV["RACK_ENV"] = 'test'
require 'server'
require 'spec_helper'

describe Link do

	context "Demonstration of how datamapper is a straight up G, foo" do
		it 'should be created and then retrieved from the db' do
			expect(Link.count).to eq(0)
			Link.create(:title => "Makers Academy",
				:url => "http://www.makersacademy.com")
			expect(Link.count).to eq(1)
			link = Link.first
			expect(link.url).to eq("http://www.makersacademy.com/")
			expect(link.title).to eq("Makers Academy")
			link.destroy
			expect(Link.count).to eq(0)
		end
	end
end

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end
